#spring.profiles.active:dev 指定配置文件为当前活跃状态
#eureka:client:serviceUrl:defaultZone: http://localhost:8070/eureka/ 找到注册发现
#eureka:
 #  client:
 #    serviceUrl:
 #      defaultZone: http://localhost:8070/eureka/
server:
  port: 8081
spring:
    #指定应用名称
#  application:
#            name: ag-user
  thymeleaf:
   cache: false
   mode: LEGACYHTML5
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: root
     url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf-8
  hikari:
        max-lifetime: 1765000 #一个连接的生命时长（毫秒）
        maximum-pool-size: 15 #连接池中允许的最大连接数。
#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.cluod.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true