eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: 8076
spring:
  application:
    name: ag-feign
#Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码：
feign:
  hystrix:
    enabled: true